name: 'Build Operator'
description: 'Build Operator'
inputs:
  image:
    description: 'Docker Image Name'
    required: true
    default: 'execDAT-operator'
  tag:
    description: 'Docker Image Tag'
    required: false
    default: 0.0.1
runs:
  using: 'composite'
  steps:
    - name: Setup Go environment
      uses: actions/setup-go@v4.0.0
    - uses: shivanshs9/setup-k8s-operator-sdk@v1
      with:
        version: "v1.28.0" # The operator-sdk version to download (if necessary) and use.
    - uses: dxas90/operator-sdk-github-action@v3
      with:
          image: '${{ inputs.image }}'
          tag: '${{ inputs.tag }}'
