# permissions for end users to view runs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: run-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: execdat-operator
    app.kubernetes.io/part-of: execdat-operator
    app.kubernetes.io/managed-by: kustomize
  name: run-viewer-role
rules:
- apiGroups:
  - task.execd.at
  resources:
  - runs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - task.execd.at
  resources:
  - runs/status
  verbs:
  - get
