apiVersion: v1
kind: Pod
metadata:
  name: test
  namespace: default
spec:
  containers:
    - imagePullPolicy: Always
      resources: {}
      name: container-0
      image: alpine
      command: 
      - "sleep"
      - "infinity"
      volumeMounts:
        - name: vol
          mountPath: /mnt
  volumes:
    - configMap:
        name: build-sample
        defaultMode: 0744
      name: vol
