apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: buildah
spec:
  privileged: false # Don't allow privileged pods!
  supplementalGroups:
    ranges:
    - max: 65535
      min: 1
    rule: MustRunAs
  runAsUser:
    rule: MustRunAsNonRoot
  volumes:
    - configMap
    - projected
  fsGroup:
    ranges:
      - max: 65535
        min: 1
    rule: MustRunAs
  allowedCapabilities:
    - SETGID
    - SETUID
  seLinux:
    rule: RunAsAny

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: buildah
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - buildah

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: buildah
roleRef:
  kind: ClusterRole
  name: buildah
  apiGroup: rbac.authorization.k8s.io
subjects:
  # Authorize all service accounts in a namespace (recommended):
  - kind: Group
    name: system:serviceaccounts
    apiGroup: rbac.authorization.k8s.io
