name: 'Buildah Container Image'
description: 'build rootless container image'
inputs:
  IMAGE_REPO:
    description: 'Repository for ghcr.io'
    required: true
    default: 'ghcr.io/execdat-operator'
  VERSION_TAG:
    description: 'Tag for image'
    required: true
    default: 'latest'
outputs: {}
runs:
  using: "composite"
  steps:
    docker:
      runs-on: ubuntu-latest
      steps:
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v2
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2
        - name: Login to Docker Hub
          uses: docker/login-action@v2
          with:
            registry: ${{ env.IMAGE_REGISTRY }}
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
        - name: Build and push
          uses: docker/build-push-action@v4
          with:
            context: "{{defaultContext}}:hack"
            platforms: linux/amd64,linux/arm64
            push: true
            tags: ${{ inputs.IMAGE_REPO }}-buildah:${{ inputs.VERSION_TAG }}
