apiVersion: task.execd.at/v1alpha1
kind: Build
metadata:
  labels:
    app.kubernetes.io/name: build
    app.kubernetes.io/instance: build-sample
    app.kubernetes.io/part-of: execdat-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: execdat-operator
  name: build-sample
spec:
  baseimage: "python:latest"
  description: "default image for demos"
  sourcecode:
    url: "https://github.com/AustrianDataLAB/execDAT"
    branch: "main"
    dependencies:
      os:
        - name: curl
          version: latest
      pip:
        - name: pandas
          version: latest
    entrypoint: python
