apiVersion: task.execd.at/v1alpha1
kind: Run
metadata:
  labels:
    app.kubernetes.io/name: run
    app.kubernetes.io/instance: run-sample
    app.kubernetes.io/part-of: execdat-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: execdat-operator
  name: run-sample
spec:
  description: "Test hunde demo 2"
  build:
    baseimage: "ubuntu:jammy"
    description: "default image for demos"
    sourcecode:
      url: "https://github.com/AustrianDataLAB/execDAT"
      branch: "feature/example"
      dependencies:
        os:
          - name: curl
            version: latest
      entrypoint: examples/entrypoint.sh
  outputdata:
    datapath: /output
  inputdata:
    url: https://www.wien.gv.at/finanzen/ogd/hunde-wien.csv
    datapath: /input
