apiVersion: task.execd.at/v1alpha1
kind: Run
metadata:
  labels:
    app.kubernetes.io/name: run
    app.kubernetes.io/instance: run-sample
    app.kubernetes.io/part-of: execdat-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: execdat-operator
  name: run-sample
spec:
  build:
    baseimage: "python:latest"
    description: "default image for demos"
    sourcecode:
      url: "https://github.com/AustrianDataLAB/execDAT"
      branch: "main"
      dependencies:
        os:
        - name: curl
          version: latest
        pip:
        - name: pandas
          version: latest
      entrypoint: python
  description: "default run"
  inputdata:
    datapath: "/data"
    transformcmd: "echo 'transform'"
    type: "https"
    url: "https://github.com/AustrianDataLAB/execDAT"
  outputdata:
    datapath: "/data/output"
    url: "https://github.com/AustrianDataLAB/execDAT"
