apiVersion: task.execd.at/v1alpha1
kind: Run
metadata:
  labels:
    app.kubernetes.io/name: run
    app.kubernetes.io/instance: run-sample
    app.kubernetes.io/part-of: execdat-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: execdat-operator
  name: run-sample
spec:
  # TODO(user): Add fields here
