# main.yml
name: Build and Release Operator
run-name: ${{ github.actor }} triggered Build and Release Operator

on: [push]

env:
  IMAGE_REGISTRY: ghcr.io
  OPERATOR_SDK_VERSION: v1.28.0
  #OPERATOR_VERSION: latest

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - name: Export Repo Name lowercase
      run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
    - name: Set Image Registry
      run: echo "IMAGE_REPO=${{ env.IMAGE_REGISTRY }}/${{ env.REPO }}" >>${GITHUB_ENV}
      # Determine the most recent release version number
    - name: Determine most recent release
      id: latest_release
      uses: actions/github-script@v6
      with:
        result-encoding: string
        script: |
          const {GITHUB_REF_NAME} = process.env
          let OPERATOR_VERSION = GITHUB_REF_NAME
          if (context.eventName == 'release' && context.action == 'published') {
            try {
              const response = await github.repos.getLatestRelease({
                owner: context.repo.owner,
                repo: context.repo.repo
              });
              OPERATOR_VERSION = JSON.stringify(response.data.tag_name);
            } catch (error) {
              OPERATOR_VERSION = "0.0.0"
            }
            core.exportVariable('IS_RELEASE', true)
          }
          core.exportVariable('OPERATOR_VERSION', OPERATOR_VERSION)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # Increment the version number by a major release
    - name: Increment major version number
      id: increment_major_version
      if: ${{ github.event_name == 'workflow_dispatch' || github.event.inputs.bump == 'major' }}
      run: echo "::set-env name=OPERATOR_VERSION::$(semver -i major ${{ env.OPERATOR_VERSION }})"

    # Increment the version number by a minor release
    - name: Increment minor version number
      id: increment_minor_version
      if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.bump == 'minor' }}
      run: echo "::set-env name=OPERATOR_VERSION::$(semver -i minor ${{ env.OPERATOR_VERSION }})"

    # Increment the version number by a patch release
    - name: Increment patch version number
      id: increment_patch_version
      if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.bump == 'patch' }}
      run: echo "::set-env name=OPERATOR_VERSION::$(semver -i patch ${{ env.OPERATOR_VERSION }})"

    - name: buildah
      uses: ./.github/actions
      id: buildah
      with:
        IMAGE_REPO: ${{ env.IMAGE_REPO }}
        VERSION_TAG: ${{ env.OPERATOR_VERSION }}

    - name: operator
      uses: ./.github/actions
      id: operator
      with:
        IMAGE_REPO: ${{ env.IMAGE_REPO }}
        VERSION_TAG: ${{ env.OPERATOR_VERSION }}
