# main.yml
on: [push]

env:
  IMAGE_REGISTRY: ghcr.io
  OPERATOR_NAME: exec-daemon
  OPERATOR_VERSION: latest

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Operator SDK
        shell: bash
        run: |
          curl -LO https://github.com/operator-framework/operator-sdk/releases/download/v${{ env.OPERATOR_SDK_VERSION }}/operator-sdk-v${{ env.OPERATOR_SDK_VERSION }}-x86_64-linux-gnu
          chmod +x operator-sdk-v${{ env.OPERATOR_SDK_VERSION }}-x86_64-linux-gnu
          mv operator-sdk-v${{ env.OPERATOR_SDK_VERSION }}-x86_64-linux-gnu /usr/local/bin/operator-sdk
        env:
          OPERATOR_SDK_VERSION: 1.28.0

      # Build the bundle image
      - name: Build bundle
        run: |
          echo "Building bundle"
          operator-sdk bundle create ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_REPO }}:${{ env.OPERATOR_VERSION }} --directory ./deploy/olm-catalog/${{ env.OPERATOR_NAME }}/ --package ${{ env.OPERATOR_NAME }} --version ${{ env.OPERATOR_VERSION }}
          docker login -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} ${{ env.IMAGE_REGISTRY }}
          docker build -t ${{ env.IMAGE_REGISTRY }}/${{ github.repository }}/${{ env.OPERATOR_NAME }}:${{ env.OPERATOR_VERSION }} ./deploy/olm-catalog/${{ env.OPERATOR_NAME }}/
